name: Generate JST Lotus RSS Feed

on:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: python -m pip install --upgrade requests beautifulsoup4 lxml

      - name: Build RSS via Python
        run: |
          python <<'PY'
          import requests, datetime, email.utils, pathlib, html
          from bs4 import BeautifulSoup

          BASE_URL = "https://www.jst.go.jp/program/india/call"
          TOP_URL = BASE_URL + "/"
          r = requests.get(TOP_URL, timeout=20)
          r.encoding = r.apparent_encoding
          soup = BeautifulSoup(r.text, "lxml")

          items = []

          # 1. 最新公募PDFリンク（1件だけ）
          a_tag = soup.select_one('p.mB40 > a')
          if a_tag:
              title = a_tag.get_text(strip=True)
              link = a_tag['href']
              if not link.startswith("http"):
                  link = BASE_URL + "/" + link.lstrip("./")
              pub = email.utils.format_datetime(datetime.datetime.utcnow())
              items.append(
                  f"<item><title>{html.escape(title)}</title><link>{link}</link><pubDate>{pub}</pubDate></item>"
              )

          # 2. 過去年度リンク
          for li in soup.select('h2:contains("過去の公募情報") + ul li'):
              a = li.find('a')
              if a:
                  title = a.get_text(strip=True)
                  link = a['href']
                  if not link.startswith("http"):
                      link = BASE_URL + "/" + link.lstrip("./")
                  pub = email.utils.format_datetime(datetime.datetime.utcnow())
                  items.append(
                      f"<item><title>{html.escape(title)}</title><link>{link}</link><pubDate>{pub}</pubDate></item>"
                  )

          rss = (
              '<?xml version="1.0" encoding="UTF-8"?>'
              '<rss version="2.0"><channel>'
              '<title>JSTインド公募 新着情報</title>'
              f'<link>{TOP_URL}</link>'
              '<description>JSTインド若手科学頭脳循環プログラム公募情報RSS</description>'
              + "".join(items) +
              '</channel></rss>'
          )
          pathlib.Path("new_rss.xml").write_text(rss, encoding="utf-8")
          print("[DEBUG] new_rss.xml created")
          PY

      - name: Show files for debug
        run: ls -lhA

      - name: Move & stage rss.xml
        run: |
          mv -f new_rss.xml rss.xml
          ls -lhA
          git add rss.xml

      - name: Commit & push if changed
        run: |
          if git diff --cached --quiet; then
            echo "Nothing to commit"; exit 0; fi
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -m "Update JST Lotus RSS feed"
          git push
